microservicio.const.test = Este es una variable de prueba dev

spring:
  datasource:
    url: jdbc:postgresql://ep-wild-smoke-a8mdmnu4-pooler.eastus2.azure.neon.tech/bdsirim?user=bdsirim_owner&password=npg_YCoxv17flmed&sslmode=require
    username: bdsirim_owner
    password: npg_YCoxv17flmed
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true